### PR TITLE
Fix nonce validation and allow extra CIC claims

### LINKED ISSUE #12: Allow additional claims to be added the CIC
We have a use case for binding a PK token to a single signature, so it would be useful to allow extra claims to be added in the CIC before it's signed by the OP.

### LINKED ISSUE #13: Have OpkClient return the PK token rather than writing it to disk

### LINKED ISSUE #16: Nonce isn't checked on validation
We don't actually check that the nonce is a hash of the CIC when verifying a PK token. The check currently reads the nonce from the PK and then checks that the PK token contains the same nonce, and of course this will always be true. We should instead construct it from the CIC.

We have a function to compute the nonce hash already which is used to get the nonce when signing, but it suffers from the same JSON key order issue mentioned at the end of #15 - I haven't checked but wouldn't be surprised if the nonces we're generating aren't actually hashes of the CIC protected headers. We should instead hash the exact bytes that are going into the JWS. This might mean that we need to do some more manual signing of the JWS rather than leaning on the jws library.

### PR DESCRIPTION
**Pull request by jonnystoten**
A few things I've fixed and added while wiring the library up in one of my projects.

Closes #12
Closes #13
Closes #16

- Fix nonce validation
- Pass extra CIC claims on sign and return on verify
- Return ID token from OidcLogin func

@EthanHeilman let me know if you'd prefer this as multiple PRs!

### CODE REVIEW

File: parties/googleclient.go [hunk 1]
```diff
@@ -64,15 +66,19 @@ func (g *GoogleOp) RequestTokens(cicHash string, cb TokenCallback) error {
...
 
 	marshalToken := func(w http.ResponseWriter, r *http.Request, tokens *oidc.Tokens[*oidc.IDTokenClaims], state string, rp rp.RelyingParty) {
 		if err != nil {
 			http.Error(w, err.Error(), http.StatusInternalServerError)
+			chErr <- err
 			return
 		}
-		cb(tokens)
 
+		ch <- []byte(tokens.IDToken)
```
Comment (EthanHeilman) [inline parties/googleclient.go:81]: Using channels rather than a callback here has been on my mental task list for longer than I'd like to admit. Thank you for doing this, so much easier to read and think about

File: parties/googleclient.go [hunk 2]
```diff
@@ -87,88 +93,124 @@ func (g *GoogleOp) RequestTokens(cicHash string, cb TokenCallback) error {
...
 
-	options := []rp.Option{
-		rp.WithVerifierOpts(rp.WithIssuedAtOffset(5*time.Second), rp.WithNonce(func(ctx context.Context) string { return string(nonce) })),
-	}
-
-	googleRP, err := rp.NewRelyingPartyOIDC(
-		g.Issuer, g.ClientID, g.ClientSecret, g.RedirectURI, g.Scopes,
-		options...)
-
+	cicphJSON, err := util.Base64DecodeForJWT(pkt.CicPH)
```
Comment (EthanHeilman) [inline parties/googleclient.go:121]: Can you think of any reason we shouldn't change the spec to hash the base64 encoding of the CIC? That way a verifier would never need to decode a CIC protected header that wasn't committed to in nonce. It would prevent someone from messing with the [unused bits in a base64 encoding.](https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-base64-decode/#:~:text=Unused%20bits&text=These%20ignored%20bits%20could%20have,first%20two%20bits%20of%20A%20.) 

This also fits closer with how JWS computes the signature:

> Compute the JWS Signature in the manner defined for the
       particular algorithm being used over the JWS Signing Input
       ASCII(BASE64URL(UTF8(JWS Protected Header)) || '.' ||
       BASE64URL(JWS Payload)). 
       
https://www.rfc-editor.org/rfc/rfc7515.html#section-5.1

File: pktoken/signer.go [hunk 3]
```diff
@@ -157,22 +151,32 @@ func (s *Signer) CreatePkToken(idtCom []byte) (*PKToken, error) {
...
 }
 
-func (s *Signer) CicSignature(payload []byte) ([]byte, error) {
+func (s *Signer) CicSignature(payload []byte) ([]byte, []byte, error) {
 	jwkPK := s.GetPubKey()
 	hdrs := jws.NewHeaders()
 	hdrs.Set(`upk`, jwkPK)
 	hdrs.Set(`rz`, s.rz)
 	hdrs.Set(`alg`, s.alg)
+	for k, v := range s.extraCIC {
```
[the remark this answers is not in the document]
Comment (jonnystoten) [reply pktoken/signer.go:186]: Good call, I've added this to places where we assign `extraCIC` so that it works for here and `ComputeNonce`

File: parties/googleclient.go (hunk 2 above)
Comment (jonnystoten) [reply parties/googleclient.go:121]: I think this is a great idea! As an aside, I guess we should we have a repo to host the spec in the openpubkey org?

Comment (EthanHeilman) [reply parties/googleclient.go:121]: Yes, I think so

**Review by EthanHeilman — APPROVED** [review]
looks good to merge
