### PR TITLE
Use GQ256 alg for GQ signatures

### LINKED ISSUE #15: GQ Signature flagging
Reading through https://github.com/bastionzero/openpubkey/pull/14 I had the following thoughts I wanted record about possible ways to flag that a signature if GQ Signature.

Consider the following two approaches:

The unsigned header flag approach
====

We flag that a OP RSA signature has been replaced by a GQ Signature by adding a unsigned header field: `"sig_type": "oidc_gq"` Lets call 

```json
{
	"payload": "payload",
	"signatures": [{
		"protected": {"alg":"ES256","rz":"5","upk":{"crv":"P-256","kty":"EC","x":"RI","y":"Hk"}},
		"header": {
			"sig_type": "cic"
		},
		"signature": "user signature"
	}, {
		"protected": {"alg":"RS256","kid":"6f7254101f56e41cf35c9926de84a2d552b4c6f1","typ":"JWT"},
		"header": {
			"sig_type": "oidc_gq"
		},
		"signature": "GQ signature"
	}]
}
```

The altered protected header approach
====

Alternatively we could alter the protected header changing the `alg` field to `GQ256` and then signing the altered protected header and payload with the GQ signature. A verifier would then reconstruct the message the OP signed with RSA by changing the algorithm field back. It would look like:

```json
{
	"payload": "payload",
	"signatures": [{
		"protected": {"alg":"ES256","rz":"5","upk":{"crv":"P-256","kty":"EC","x":"RI","y":"Hk"}},
		"header": {
			"sig_type": "cic"
		},
		"signature": "user signature"
	}, {
		"protected": {"alg":"GQ256","kid":"6","typ":"JWT"},
		"signature": "GQ signature"
	}]
}
```

Comparison
====

**The unsigned header flag approach**

**Pros:**
* Results in a simpler implementation of the the verifier and the signer.
* None of the values which are signed by OP are altered or reserialized.

**Cons:**
* Standard OIDC validators don't know about GQ signatures or the `sig_type` header so they will likely attempt to verify the GQ signature as if it was a very large RSA signature resulting in a hard to debug failure.
* Uses an unsigned header, which means we have to worry about what happens if someone alters this header. Ideally there is no content which is not covered by a signature. This is a minor con.

**The altered protected header approach**

**Pros:**
* Standard OIDC validators will see that the `alg` is set to algorithm they don't support and fail gracefully producing a meaningful error message: Signature algorithm `GQ256` is unsupported.
* If we want to standardize GQ signatures in JWS as `alg` is the standard way of flagging the signing algorithm

**Cons:**
* Likely a source of bugs and a pain point for implementors. Changing the protected header requires serializing and deserializing it. Different JSON libraries make minor changes to whitespace or the ordering of keys that result in signatures not verifying. These signature verification issues can creep in both when generating the GQ signature and when verifying it, as they both involve deserializing the protected header, making a change and then serializing it again.

We could bypass this con by storing the base64 encoding of the OPs signature in the protected header. That seems a little abusive toward the JWS standard.

### PR DESCRIPTION
**Pull request by jonnystoten**
Closes #15.

For GQ signatures, we take the original ID token from the OIDC provider and replace the header. The new header is the same as the original with two changes:

1. The `alg` claim is set to `GQ256`
2. The `kid` claim is set to the original header value from the ID token. This value is taken directly from the JWT token signing payload (raw base64 encoded)

The `alg` value gives us an easy way to identify the GQ signature from a JWS containing multiple signatures. The `kid` claim allows us to recreate the original signing payload in order to verify the signature.

For example, an ID token header of
```json
{"alg":"RS256","typ":"JWT"}
```
would be replaced with a new header:
```json
{"alg":"GQ256","kid":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9","typ":"JWT"}
```

### CODE REVIEW

File: client/providers/google.go [hunk 1]
```diff
@@ -120,12 +120,19 @@ func (g *GoogleOp) VerifyCICHash(ctx context.Context, idt []byte, expectedCICHas
...
-func (g *GoogleOp) PublicKey(ctx context.Context, idt []byte) (crypto.PublicKey, error) {
-	j, err := jws.Parse(idt)
+func (g *GoogleOp) PublicKey(ctx context.Context, headersEnc []byte) (crypto.PublicKey, error) {
+	headersJSON, err := util.Base64DecodeForJWT(headersEnc)
 	if err != nil {
-		return nil, fmt.Errorf("failed to parse JWS: %w", err)
+		return nil, err
+	}
+
+	headers := make(map[string]any)
```
Comment (whalelines) [inline client/providers/google.go:129]: Why would the headers not be `map[string]string`? Is something unmarshalling the strings into something else?

Comment (whalelines) [inline client/providers/google.go:129]: Why would the headers not be `map[string]string`? Is something unmarshaling the strings into something else?

**Review by whalelines — COMMENTED** [review]
Is part of the un-drafting to add tests?

File: client/providers/google.go (hunk 1 above)
Comment (jonnystoten) [reply client/providers/google.go:129]: You're right, this is just me being lazy

**Comment by jonnystoten** [comment]
> Is part of the un-drafting to add tests?

Yes!

File: client/providers/google.go (hunk 1 above)
Comment (whalelines) [reply client/providers/google.go:129]: I don't know if forcing yourself to cast to string every time you need to use it counts as laziness.

**Comment by EthanHeilman** [comment]
Instead of using the JOSE header `orig` to specify the original protected header, what about storing the original protected header in the `kid`.

```golang
headers["orig"] = string(origHeaders)
```
vs.

```golang
headers["kid"] = string(origHeaders)
```

**Pros:**
1. Avoids definining a novel JOSE header, `orig`, Some libraries that only support known JOSE headers.
2. `kid` is designed to specify a JWK which is what what the original protected header itself does. It is common to assign `kid` as a Public key hashes and fingerprints

**Cons:**
1. Could be confusing as it overloads the meaning of the `kid`. The header name `orig` has a more explicit meaning. Generally you don't deserialize a `kid`.

>The "kid" (key ID) Header Parameter is a hint indicating which key was used to secure the JWS.  This parameter allows originators to explicitly signal a change of key to recipients.
https://www.rfc-editor.org/rfc/rfc7515.html

**Comment by jonnystoten** [comment]
I think that's a good idea. It will make it slightly easier to use the jwx library to get the original headers out - the library makes it hard to use non-standard headers.

You trimmed your quote early there, the next sentence is

> The structure of the "kid" value is unspecified.

which means it would be valid according to the spec.

File: client/providers/google.go (hunk 1 above)
Comment (jonnystoten) [reply client/providers/google.go]: I originally changed this to unmarshal to a struct, but on second thought, I think the map[string]any is better. This is untrusted input so it really could be anything, and when unmarshalling into a struct, if the key is missing we'll just get an empty string. With a map we can check it's there and the correct type.

File: client/oidc.go [hunk 2]
```diff
@@ -89,6 +99,52 @@ func VerifyPKToken(ctx context.Context, pkt *pktoken.PKToken, provider OpenIdPro
 	return nil
 }
 
+func DiscoverPublicKey(ctx context.Context, headersEnc []byte, issuer string) (crypto.PublicKey, error) {
```
Comment (EthanHeilman) [inline client/oidc.go:102]: I've tried to use a postfix of `B64` to signal that a variable is Base64 encoded and I'd like to maintain that as a convention: `headersEnc` to `headersB64`.

File: client/oidc.go [hunk 3]
```diff
@@ -89,6 +99,52 @@ func VerifyPKToken(ctx context.Context, pkt *pktoken.PKToken, provider OpenIdPro
...
+	if err != nil {
+		return nil, fmt.Errorf("failed to fetch to JWKS: %w", err)
+	}
+
+	key, ok := jwks.LookupKeyID(kid)
+	if !ok {
+		return nil, fmt.Errorf("key %q isn't in JWKS", kid)
+	}
+
+	pubKey := new(rsa.PublicKey)
```
Comment (EthanHeilman) [inline client/oidc.go:139]: Before casting to a particular key type, say RSA, we should check that the algorithm of the returned JWK matches the key type we are casting to. This is similar to my comment above, but unless I am mistaken, I think we should do this check in both places.

Your PR does not introduce this issue as it exists in the current code, but it is a valuable check to have.

File: pktoken/pktoken.go [hunk 4]
```diff
@@ -192,31 +198,39 @@ func (p *PKToken) UnmarshalJSON(data []byte) error {
...
+		if len(pubMap) == 0 {
+			signature.SetPublicHeaders(nil)
 		}
 
-		sigHeaderString, ok := sigHeader.(string)
+		protected := signature.ProtectedHeaders()
+		typeHeader, ok := protected.Get(jws.TypeKey)
+		if !ok {
+			// TODO: default to OIDC?
+			return fmt.Errorf("missing typ header")
```
Comment (EthanHeilman) [inline pktoken/pktoken.go:213]: I believe should default to OIDC here since it is completely within the JWS standard to not include a `typ` header. OpenPubkey should always include a `typ` header for a COS and CIC signature.

It might make sense to log a warning, because it is very uncommon for a OP to not include a `typ` header. It is happens, it is probably a since of some weirdnesss.

**Review by EthanHeilman — CHANGES_REQUESTED** [review]
Not a full complete review, but I wanted to write these two issues down

File: client/oidc.go (hunk 3 above)
Comment (jonnystoten) [reply client/oidc.go:139]: I think this is already OK because the jwx library does this check itself. The key is parsed after being fetched and stored in an appropriate struct based on the `alg` field (see https://github.com/lestrrat-go/jwx/blob/262da1ab53fc42371eb8a13ae61044589b1a239b/jwk/jwk.go#L443-L467). Then `key.Raw(pubKey)` checks that `pubKey` is of the appropriate type for the type of `key` and errors otherwise.

File: client/oidc.go [hunk 5]
```diff
@@ -41,15 +46,20 @@ func VerifyPKToken(ctx context.Context, pkt *pktoken.PKToken, provider OpenIdPro
...
+	switch alg {
+	case gq.GQ256:
+		origHeaders, err := gq.OriginalJWTHeaders(idt)
+		if err != nil {
+			return err
+		}
+
 		// TODO: this needs to get the public key from a log of historic public keys based on the iat time in the token
-		pubKey, err := provider.PublicKey(ctx, idt)
+		pubKey, err := provider.PublicKey(ctx, origHeaders)
```
[the remark this answers is not in the document]
Comment (jonnystoten) [reply client/oidc.go:62]: For (1) I think we should first check that the `alg` claim in `origHeaders` is RS256, then just check that the key returned from `provider.PublicKey` is actually `*rsa.PublicKey`. At the moment this code will panic if it isn't!

For (2), totally agree, I'll add that check.

File: client/oidc.go [hunk 6]
```diff
@@ -89,6 +99,52 @@ func VerifyPKToken(ctx context.Context, pkt *pktoken.PKToken, provider OpenIdPro
...
+	jwks, err := jwk.Fetch(ctx, discConf.JwksURI)
+	if err != nil {
+		return nil, fmt.Errorf("failed to fetch to JWKS: %w", err)
+	}
+
+	key, ok := jwks.LookupKeyID(kid)
+	if !ok {
+		return nil, fmt.Errorf("key %q isn't in JWKS", kid)
+	}
+
```
Comment (EthanHeilman) [inline client/oidc.go:138]:
```suggestion
	if key.Algorithm() != jwa.SignatureAlgorithm.RS256 {
		return nil, fmt.Errorf("unsupported alg (%q) in JWK with kid (%q) for OP (%q), OpenPubkey only alg=RS256 supported: \n", key.Algorithm(), kid, issuer)
	}
```

File: client/oidc.go (hunk 3 above)
Comment (EthanHeilman) [reply client/oidc.go:139]: You are correct I misread what the code was doing here.

It might save a future dev some time if we create a custom error for the case where the key is not RS256. I've made a suggestion for this above. Not a requirement for this PR so feel free to reject the suggestion and resolve this comment.

Comment (jonnystoten) [reply client/oidc.go:139]: Yes, good idea. I'll tweak the suggestion slightly

**Comment by EthanHeilman** [comment]
Manually tested this using the google example with GQ signatures on and off and inspected the PK Tokens. Every thing works and looks as expected.

Details included only for the sake of posterity:

OP signature pheader (GQ=true)
```json
{"alg":"GQ256","kid":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjliMDI4NWMzMWJmZDhiMDQwZTAzMTU3YjE5YzRlOTYwYmRjMTBjNmYiLCJ0eXAiOiJKV1QifQ","typ":"JWT"}
```

Decoded signature from `kid`
```json
{"alg":"RS256","kid":"9b0285c31bfd8b040e03157b19c4e960bdc10c6f","typ":"JWT"}
```

CIC signature:
```json
{"alg":"ES256","extra":"yes","rz":"ac8dbe1734c088b118b6a7e9fd0a6d9f1142ee6ff0d5b9eea9d2fac10299e135","typ":"CIC","upk":{"alg":"ES256","crv":"P-256","kty":"EC","x":"ApbgXJU728FDasOsnZs2uVxzmLT6UosyQoYCunuBhTk","y":"B5b5U9C_kzOr5ta06-ffZnZDYK6OoJXT9WW3cQjbYrg"}}
```
We do include the alg in both upk JWK object and at the pheader which is annoying. Might be worth addressing that at some point, but not in this PR.

OP signature pheader (GQ=false)
```json
{"alg":"RS256","kid":"9b0285c31bfd8b040e03157b19c4e960bdc10c6f","typ":"JWT"}
```

**Review by EthanHeilman — APPROVED** [review]
Tested manually, LGTM

**Review by EthanHeilman — APPROVED** [review]
LGTM
